print('TrashTrashTrashTrashTrashTrashTrashTrashTrashTrash')
print('CleanCleanCleanCleanCleanCleanCleanCleanCleanClean')
print('CleanCleanCleanCleanCleanCleanCleanCleanCleanClean')
print('TrashTrashTrashTrashTrashTrashTrashTrashTrashTrash')
